---
title: "Untitled"
author: "Andrew Saul"
date: "14/02/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if(!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(tidyverse, here, fs, rvest ,xml2, openxlsx, lubridate, readxl, janitor, glue, rlang)
source(here::here("scripts", "my_funcs.R"))
source(here::here("scripts", "populations.R"))
```

```{r historical-stats}
#download excel files if not already in directory
if(!is_file(here::here("data","females_pop.xlsx"))|
   !is_file(here::here("data","males_pop.xlsx"))) download_pop_data()

raw_pop_2020 <- create_population_tibble()

# vector "Council_areas" containing LA areas
Council_areas <- raw_pop_2020 %>% 
  select(CouncilArea) %>% 
  unique() %>% 
  pull()

# Population 18+ in "Council_areas"
LA_pop_18plus <- raw_pop_2020 %>% 
  group_by(CouncilArea) %>% 
  summarise(Pop = sum(Pop))


```

```{r}
#download from NRS website
# if not downloading, copy link of excel data file and paste as argument
# in download_data(url =  copied link)
 # name of file to be saved is "beddays.xlsx"
data_filename <- "beddays"
download_data(filename = data_filename)

# save pathname of excel file to xl_file object
xl_file <- here::here("data", data_filename)

#create a single tibble containing both healthboard and LA data
tib <- map_dfr(create_sheetname_vector(xl_file), 
              ~create_FY_authority(xl_file, sheet_name = .x)) 

```

