---
title: "Untitled"
author: "Andrew Saul"
date: "14/02/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 10, fig.height = 6)
Report_month <- "December"
```

```{r include = "FALSE"} 
if(!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(tidyverse, here, fs, rvest ,xml2, openxlsx, lubridate, readxl, janitor, glue, rlang, plotly, ggtext)
source(here::here("scripts", "my_funcs.R"))
source(here::here("scripts", "populations.R"))
```

```{r historical-stats}
# getLAPops acquires pop data stored in an .rds file
#find pops for ages>= 18 for all LAs and Scotland
# NO SCOTLAND POP DATA WITH THIS .RDS

# no data available for mid-pop estimate for 2021.  
# locf (last observation carried forward) utilised from 2020 for 2021
#Scotland pop values created by summing all CouncilAreas.
LA_pop_18plus <- getLAPops(age_lowest = 18)

```

```{r download-NRS-recent-data}
#file downloaded from NRS website if filename not present in data folder
data_filename <- "beddays"
#if(!file_exists(here::here("data", glue("{data_filename}.xlsx")))){
#download_data(filename = data_filename)

```

```{r convert-to-tibbles}
# save pathname of beddays xlsx file to object 
xl_file <- here::here("data", glue("{data_filename}.xlsx"))

#create a single tibble containing both healthboard and LA data, as "Scotland" located in HB... sheets. Only "Scotland" kept from HB... sheets 
# change format of FY (eg 1718)to year of start FY (2017)
raw_tib <- map_dfr(create_sheetname_vector(xl_file), # vector of LA and HB data from FY 12/13 until 21/22
              ~create_FY_authority(xl_file, sheet_name = .x)) 

######################################################################################
#create tibble with FY to date 
tib_fytd <- raw_tib %>% 
  select("CouncilArea", "AgeGroup", "ComplexNeedsFlag", "FYToDate", "FY", "FY_begin") %>% 
  rename(Counts = FYToDate) %>% 
  add_GGC_field()

######################################################################################
#create tibble with Month/Year Counts
# used to 1- select columns for pivoting & 2- set order of months
month_order <- c("April", "May", "June", "July", "August", "September",
                   "October", "November", "December", "January", "February",
                   "March")

tib_FY_CA<- get_FY_CA_data(raw_tib) %>% 
  add_GGC_field()

```

```{r data}
#############################
#fydata is in format "yy/yy"#
#############################

#Scotland values obtained from HBData sheets

# use scot_flag = TRUE to get Scotland values,
# use ggc_flag = TRUE to get GGC values
# use month_flag = FALSE if calculating FY to date values

# Dec 2021 Code9 rates
############Scotland######################
## December 2021##
# scot_code9_mon <- get_group_bed_rates(tib_FY_CA, CNeeds_string = "Code 9",  fydate=2122, mon= "December", ggc_flag = FALSE, scot_flag = TRUE) %>% 
#   get_group_bedrate_value()
# 
# scot_standard_mon <- get_group_bed_rates(tib_FY_CA, CNeeds_string = "Standard",  fydate=2122, mon= "December", ggc_flag = FALSE, scot_flag = TRUE) %>% 
#   get_group_bedrate_value()
# 
# ## up to Dec 2021 Scotland figures ##
# scot_code9_year_agg <- get_group_bed_rates(tib_fytd, CNeeds_string = "Code 9", fydate=2122, ggc_flag = FALSE, scot_flag = TRUE)  %>% 
#   get_group_bedrate_value()
# 
# scot_standard_year_agg <- get_group_bed_rates(tib_fytd, CNeeds_string = "Standard", fydate=2122, ggc_flag = FALSE, scot_flag = TRUE)  %>% 
#   get_group_bedrate_value()
# 
# ################GGC group value#################
# ## Dec 2021 ##
# ggc_code9_mon <- get_group_bed_rates(tib_FY_CA, CNeeds_string = "Code 9", fydate=2122,  mon = "December", ggc_flag = TRUE) %>% 
#   get_group_bedrate_value()
# 
# ggc_standard_mon <- get_group_bed_rates(tib_FY_CA, CNeeds_string = "Standard", fydate=2122,  mon = "December", ggc_flag = TRUE) %>% 
#   get_group_bedrate_value()
# 
# ## up to Dec 2021 ##
# ggc_code9_year_agg <- get_group_bed_rates(tib_fytd,  CNeeds_string = "Code 9", fydate=2122, ggc_flag = TRUE)  %>% 
#   get_group_bedrate_value()
# 
# ggc_standard_year_agg <- get_group_bed_rates(tib_fytd,  CNeeds_string = "Standard", fydate=2122, ggc_flag = TRUE)  %>% 
#   get_group_bedrate_value()
# ######## All Council Areas ################################################
# ## December ##
# tib_code9_mon <- get_group_bed_rates(tib_FY_CA, CNeeds_string = "Code 9", fydate=2122, mon = "December") %>% 
#   filter(CouncilArea != "Scotland")
# 
# tib_standard_mon <- get_group_bed_rates(tib_FY_CA, CNeeds_string = "Standard", fydate=2122, mon = "December") %>% 
#   filter(CouncilArea != "Scotland")
# 
# ## up to Dec FY##
# tib_code9_yearagg <- get_group_bed_rates(tib_fytd, CNeeds_string ="Code 9", fydate=2122) %>% 
#   filter(CouncilArea != "Scotland")
# 
# tib_standard_yearagg <- get_group_bed_rates(tib_fytd, CNeeds_string ="Standard", fydate=2122) %>% 
#   filter(CouncilArea != "Scotland")

```

```{r currentplots}
# create_CArate_plot <- function(tib, CNeeds_string, fydate){
#   
#   mon <- tib %>% slice(1) %>% select(Months) %>% pull() %>% as.character()
#   FYear <- seperate_years_by_slash(fydate)
#   ggplot(tib, aes(x=reorder(CouncilArea, Rate), y=Rate, fill = GGCRegion))+
#     geom_col()+
#     geom_text(aes(label = format(signif(as.integer(Rate,3)))), hjust = 1, colour = "white") +
#     scale_fill_manual(name= "GGC Area", values =c("#0078D4", "#83bb26"))+
#     guides(fill = guide_legend(reverse=TRUE))+
#     coord_flip()+
#     labs(title = str_wrap(glue("{mon} FY({FYear}) – {CNeeds_string} Delays : Rate per 100,000 Population")),
#            y = str_wrap("Bed Days Rate (Per 100,000 Population)"),
#            x= "")+
#       #guides(linetype = guide_legend(order = 2), fill = guide_legend(order = 1), color = guide_legend(order = 1))+
#       theme_set(theme_minimal(base_size = 12, base_family = "Open Sans"))+
#       theme_update(
#         axis.ticks = element_line(color = "grey92"),
#         axis.ticks.length = unit(.5, "lines"),
#         panel.grid.minor = element_blank(),
#         legend.title = element_text(size = 12),
#         legend.text = element_text(color = "grey30"),
#         plot.title = element_text(size = 18, face = "bold"),
#         plot.subtitle = element_text(size = 12, color = "grey30"),
#         plot.caption = element_text(size = 9, margin = margin(t = 15))
#       )
# }
# 

```

```{r}
# tib = either tib_FY_CA or tib_fytd

create_current_rateplot <- function(tib, CNeeds_string, fydate, mon=NULL) {

#scot_rate and ggc_rate are lists containing the numeric value and the displayed char value to 1 dp
#get scotland rate
  scot_rate <-   get_group_bed_rates(tib, CNeeds_string, fydate, mon, ggc_flag=FALSE, scot_flag=TRUE) %>% 
    get_group_bedrate_value()


    #get ggc_rate    
      
    ggc_rate <- get_group_bed_rates(tib, CNeeds_string, fydate, mon, ggc_flag=TRUE, scot_flag=FALSE) %>% 
      get_group_bedrate_value()

   # ggc_rate <- get_group_bedrate_value(ggc_rate)
# 
#     #get_all_CA_rates
     all_CA_rates <-  get_group_bed_rates(tib, CNeeds_string, fydate, mon) %>%
     filter(CouncilArea != "Scotland")
    # 
    #list(scot_rate, ggc_rate, all_CA_rates)
#     
# # plot horizontal column plot
  create_CArate_plot(df=all_CA_rates, CNeeds_string, fydate, mon, ggc_rate, scot_rate)
    #list(scot_rate, ggc_rate, all_CA_rates)

}

```


```{r prev5yr}
# #Previous 5 year data excluding year 2021
# #Vector of Council Areas
all_CA_names <- get_council_area_names(tib_FY_CA) # all regions
CA_of_interest <- c("Scotland", "East Dunbartonshire", "East Renfrewshire", "Glasgow City", "Inverclyde", "Renfrewshire", "West Dunbartonshire")
fydate <- 2122
CNeeds_list <- c("Code 9", "Standard")


#list of all Councils containing tibbles for min,max, avg current values

 all_rates <- get_prev_7yr_rates(tib_FY_CA, CNeeds_list, CA_of_interest)

# for (CNeeds_element in CNeeds_list){
# all_rates[CNeeds_element] <- map(CNeeds_list, map(CA_names, ~get_rates(tib=tib_FY_CA, CA= .x, CNeeds_string = CNeeds_element, fydate= fydate, pop_objfile=LA_pop_18plus)) %>%
#   set_names(., CA_names)
# }

#map(all_rates, create_5yr_plot)

# Index contains the elements seq_along(CA_of_interest)
#create_7yr_plot(tibble_name = all_rates, index=1, CNeeds_string ="Standard", CA_of_interest)



```

```{r}
all_rates <- get_prev_7yr_rates(tib_FY_CA, CNeeds_list, CA_of_interest)
```



## Code 9 Results {.tabset}

### `r Report_month`

```{r}
create_current_rateplot(tib=tib_FY_CA, CNeeds_string = "Code 9", fydate = "2122", mon = Report_month)

```

### FY to Date

```{r}
create_current_rateplot(tib=tib_fytd, CNeeds_string = "Code 9", fydate = "2122", mon=NULL)
```

### `r CA_of_interest[1]`

```{r}
create_7yr_plot(tibble_name = all_rates, index=1, CNeeds_string ="Code 9", CA_of_interest = CA_of_interest)
```


## Standard Results {.tabset}

### `r Report_month`

```{r}
create_current_rateplot(tib=tib_FY_CA, CNeeds_string = "Standard", fydate = "2122", mon = Report_month)
```

### FY to Date

```{r}
create_current_rateplot(tib=tib_fytd, CNeeds_string = "Standard", fydate = "2122", mon=NULL)
```



